In [2]:
import pandas as pd
import numpy as np

In [30]:
!ls /data/qs4-data2/PPO-with-Confidence/data/halfsplit

PPO_data_27026_as_nutribench.csv  SFT_data_28025.json
PPO_data_27026.json		  validation_data_1000.json
SFT_data_28025_as_nutribench.csv

In [19]:
!rm /data/qs4-data2/PPO-with-Confidence/data/halfsplit/SFT_data_28025_as_nutribench
!rm /data/qs4-data2/PPO-with-Confidence/data/halfsplit/PPO_data_27026_as_nutribench

In [1]:
DATA_DIR = '/data/qs4-data2/PPO-with-Confidence/data/halfsplit/'
NUTRIBENCH_PATH = 'hf://datasets/dongx1997/NutriBench/v2/train-00000-of-00001.parquet'

SFT_FILE_NAME = 'SFT_data_28025.json'
PPO_FILE_NAME = 'PPO_data_27026.json'

SFT_FILE_PATH = DATA_DIR + SFT_FILE_NAME
PPO_FILE_PATH = DATA_DIR + PPO_FILE_NAME

SFT_FILE_PATH_AS_NUTRIBENCH = DATA_DIR + SFT_FILE_NAME.split('.')[0] + '_as_nutribench.csv'
PPO_FILE_PATH_AS_NUTRIBENCH = DATA_DIR + PPO_FILE_NAME.split('.')[0] + '_as_nutribench.csv'

In [3]:
sft_df = pd.read_json(SFT_FILE_PATH)
ppo_df = pd.read_json(PPO_FILE_PATH)

# sft_df.rename(columns={'question': 'meal_description',
#                        'answer_value': 'carb'}, inplace=True)
# ppo_df.rename(columns={'question': 'meal_description',
#                           'answer_value': 'carb'}, inplace=True)

In [4]:
sft_df.head()

,item_id,answer_cot,answer_value,question
0,nutri_20615,The meal consists of 100 grams of dark chocola...,70.83,Enjoying 100 grams of dark chocolate almond bi...
1,nutri_40265,The meal consists of 227g DIGIORNO supreme top...,63.40,227 grams of DIGIORNO supreme topping pizza wi...
2,nutri_23,The meal consists of a cup of diced raw rhubar...,5.54,A cup filled with diced raw rhubarb.
3,nutri_41461,The meal consists of 100 grams of whole chili ...,71.43,100 grams of whole chili peppers.
4,nutri_37236,The meal consists of 100g Raisin & Honey Scand...,60.00,100 grams of Raisin & Honey Scandinavian Crisp...

In [5]:
ppo_df.head()

,item_id,answer_cot,answer_value,question
0,nutri_52357,The meal consists of 100 grams of SONNY & JOE'...,90.15,Enjoying a portion of SONNY & JOE'S HUMMUS GAL...
1,nutri_28943,The meal consists of 100 grams of Creme Earl G...,41.67,I possess 100 grams of Earl Grey black tea in ...
2,nutri_47268,The meal consists of 100 grams of peeled red a...,42.70,"For a snack, I am enjoying 100 grams of peeled..."
3,nutri_23801,The meal consists of 153 grams of chicken and ...,8.23,I placed an order for 153 grams of chicken alo...
4,nutri_12927,The meal consists of a cup of cooked hyacinth ...,10.20,A cup of boiled hyacinth beans seasoned with s...

In [6]:
ppo_csv = pd.read_csv(PPO_FILE_PATH_AS_NUTRIBENCH)
ppo_csv

,item_id,answer_cot,carb,meal_description
0,nutri_52357,The meal consists of 100 grams of SONNY & JOE'...,90.15,Enjoying a portion of SONNY & JOE'S HUMMUS GAL...
1,nutri_28943,The meal consists of 100 grams of Creme Earl G...,41.67,I possess 100 grams of Earl Grey black tea in ...
2,nutri_47268,The meal consists of 100 grams of peeled red a...,42.70,"For a snack, I am enjoying 100 grams of peeled..."
3,nutri_23801,The meal consists of 153 grams of chicken and ...,8.23,I placed an order for 153 grams of chicken alo...
4,nutri_12927,The meal consists of a cup of cooked hyacinth ...,10.20,A cup of boiled hyacinth beans seasoned with s...
...,...,...,...,...
27021,nutri_45291,The meal consists of 100 grams of TASTE OF INS...,60.00,100 grams of TASTE OF INSPIRATIONS French Vani...
27022,nutri_1278,The meal consists of 100 ml MEAD JOHNSON ENFAM...,9.25,A 100 ml portion of ready-to-feed MEAD JOHNSON...
27023,nutri_22514,The meal consists of 100 grams of Tyson Fully ...,16.17,Consuming 100 grams of Tyson Fully Cooked Hot ...
27024,nutri_29484,The meal consists of 105g oat bran bagel.\n105...,55.97,"For breakfast, I enjoyed an oat bran bagel wei..."
27025,nutri_37327,The meal consists of 100 grams of Tuttorosso B...,8.20,100 grams of Tuttorosso Blue crushed tomatoes ...

In [7]:
nutribench_df = pd.read_parquet(NUTRIBENCH_PATH)
nutribench_df.head()

,meal_description,carb,fat,energy,protein,country,serving_type
0,"For breakfast, I ate a plain bun weighing 126 ...",90.8,4.2,439.0,9.6,ZMB,metric
1,"For lunch, I had 171 grams of boiled fresh gro...",97.8,37.8,806.0,27.9,ZMB,metric
2,"I’ve got 9 grams of boiled kasepa fish, 34 gra...",51.2,14.2,363.0,8.7,ZMB,metric
3,I had a breakfast consisting of 51g of raw whi...,163.8,8.9,792.0,19.0,ZMB,metric
4,"For dinner, I had 105g of raw maize flour alon...",81.1,4.6,390.0,8.4,ZMB,metric

In [29]:
sft_df.to_csv(SFT_FILE_PATH_AS_NUTRIBENCH, index=False)
ppo_df.to_csv(PPO_FILE_PATH_AS_NUTRIBENCH, index=False)

In [7]:
nutribench = pd.read_parquet(NUTRIBENCH_PATH)
nutribench

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 3985edd9-63ca-4df2-9431-d6fb6599c86e)')' thrown while requesting GET https://huggingface.co/datasets/dongx1997/NutriBench/resolve/main/v2/train-00000-of-00001.parquet
Retrying in 1s [Retry 1/5].

,meal_description,carb,fat,energy,protein,country,serving_type
0,"For breakfast, I ate a plain bun weighing 126 ...",90.80,4.20,439.00,9.60,ZMB,metric
1,"For lunch, I had 171 grams of boiled fresh gro...",97.80,37.80,806.00,27.90,ZMB,metric
2,"I’ve got 9 grams of boiled kasepa fish, 34 gra...",51.20,14.20,363.00,8.70,ZMB,metric
3,I had a breakfast consisting of 51g of raw whi...,163.80,8.90,792.00,19.00,ZMB,metric
4,"For dinner, I had 105g of raw maize flour alon...",81.10,4.60,390.00,8.40,ZMB,metric
...,...,...,...,...,...,...,...
15612,"For dinner, I'm having a cup of prepared noodl...",40.79,12.52,299.56,6.28,USA,natural
15613,I'm snacking on a cup of banana chips.,42.05,24.19,373.68,1.66,USA,natural
15614,I’ve got a piece of chewing gum along with a 6...,7.89,0.01,29.19,0.00,USA,natural
15615,"For breakfast, I'm having a McDonald's sandwic...",39.68,27.69,523.20,27.47,USA,natural
15616,I’m having a 2 oz chocolate-covered peanut bar...,29.14,18.50,299.82,7.45,USA,natural